Task.create(status: false, task:"Hacer tarea")
Task.create(status: false, task:"Comprar manzanas rojas")
Task.create(status: false, task:"Lavar la ropa")
Task.create(status: false, task:"Convertirme en un Developer Rock Star")
Task.create(status: false, task:"Añadir una tarea")
Task.create(status: true, task:"Ver las tareas")
Task.create(status: false, task:"Eliminar tarea")
Task.create(status: false, task:"Marcar una tarea como completada")
Task.create(status: false, task:"Guardar en CSV")
Task.create(status: true, task:"terminar este programa")
Task.create(status: false, task:"Preparar la comida")
Task.create(status: false, task:"compar verdura")
Task.create(status: true, task:"Limpiar el departamento")
Task.create(status: false, task:"Lavar los trastes")
Task.create(status: false, task:"Hacer el resumen")