
#TODAS ESTAS SE TIENEN QUE MODIFICAR!!!!! lo guardo para conservar la estructura

#Users
 User.create(name: "Diana", email: "diana@mail.com", password: "manolo1" )
 User.create(name:"Chuy", email: "chuy@mail.com", password: "manolo2")
 User.create(name:"Mayra", email: "may@mail.com", password: "manolo3")

 #Decks
 Deck.create(subject: "Mexico")
 Deck.create(subject: "America")
 Deck.create(subject: "Europa")

#Questions Deck1
Question.create(deck_id: 1, text: "Guanajuato")
Question.create(deck_id: 1, text: "Baja California Sur")
Question.create(deck_id: 1, text: "Baja California Norte")
Question.create(deck_id: 1, text: "Campeche")
Question.create(deck_id: 1, text: "Coahuila")
Question.create(deck_id: 1, text: "Aguascalientes")
Question.create(deck_id: 1, text: "Jalisco")
Question.create(deck_id: 1, text: "México")
Question.create(deck_id: 1, text: "Michoacan")
Question.create(deck_id: 1, text: "Nuevo León")

#Questions Deck2
Question.create(deck_id: 2, text: "Argentina")
Question.create(deck_id: 2, text: "Brazil")
Question.create(deck_id: 2, text: "Colombia")
Question.create(deck_id: 2, text: "Belice")
Question.create(deck_id: 2, text: "Bolivia")
Question.create(deck_id: 2, text: "Chile")
Question.create(deck_id: 2, text: "Canada")
Question.create(deck_id: 2, text: "México")
Question.create(deck_id: 2, text: "Peru")
Question.create(deck_id: 2, text: "Haití")

#Questions Deck3
Question.create(deck_id: 3, text: "Francia")
Question.create(deck_id: 3, text: "España")
Question.create(deck_id: 3, text: "Italia")
Question.create(deck_id: 3, text: "Alemania")
Question.create(deck_id: 3, text: "Inglaterra")
Question.create(deck_id: 3, text: "Polonia")
Question.create(deck_id: 3, text: "Belgica")
Question.create(deck_id: 3, text: "Autria")
Question.create(deck_id: 3, text: "Grecia")
Question.create(deck_id: 3, text: "Dinamarca")

#Answers Deck 1
Answer.create(question_id: 1, option: "Guanajuato", status: true)
Answer.create(question_id: 1, option: "León", status: false)
Answer.create(question_id: 1, option: "Silao", status: false)
Answer.create(question_id: 2, option: "La Paz", status: true)
Answer.create(question_id: 2, option: "Los Cabos", status: false)
Answer.create(question_id: 2, option: "Mexicali", status: false)
Answer.create(question_id: 3, option: "Mexicali", status: true)
Answer.create(question_id: 3, option: "Ensenada", status: false)
Answer.create(question_id: 3, option: "Tijuana", status: false)
Answer.create(question_id: 4, option: "Campeche", status: true)
Answer.create(question_id: 4, option: "Ciudad del Carmen", status: false)
Answer.create(question_id: 4, option: "Merida", status: false)
Answer.create(question_id: 5, option: "Saltillo", status: true)
Answer.create(question_id: 5, option: "Coahuila", status: false)
Answer.create(question_id: 5, option: "Colima", status: false)
Answer.create(question_id: 6, option: "Aguascalientes", status: true)
Answer.create(question_id: 6, option: "San Marcos", status: false)
Answer.create(question_id: 6, option: "Tepa", status: false)
Answer.create(question_id: 7, option: "Guadalajara", status: true)
Answer.create(question_id: 7, option: "Jalisco", status: false)
Answer.create(question_id: 7, option: "Tequila", status: false)
Answer.create(question_id: 8, option: "Toluca", status: true)
Answer.create(question_id: 8, option: "DF", status: false)
Answer.create(question_id: 8, option: "México", status: false)
Answer.create(question_id: 9, option: "Moleria", status: true)
Answer.create(question_id: 9, option: "Janitzio", status: false)
Answer.create(question_id: 9, option: "Patzcuaro", status: false)
Answer.create(question_id: 10, option: "Monterrey", status: true)
Answer.create(question_id: 10, option: "Apodaca", status: false)
Answer.create(question_id: 10, option: "San Jose", status: false)

#Answers deck2
Answer.create(question_id: 11, option: "Buenos Aires", status: true)
Answer.create(question_id: 11, option: "Santigo", status: false)
Answer.create(question_id: 11, option: "San José", status: false)
Answer.create(question_id: 12, option: "Brasília", status: true)
Answer.create(question_id: 12, option: "Río de Janeiro", status: false)
Answer.create(question_id: 12, option: "San José", status: false)
Answer.create(question_id: 13, option: "Bogotá", status: true)
Answer.create(question_id: 13, option: "Medellin", status: false)
Answer.create(question_id: 13, option: "Santiago", status: false)
Answer.create(question_id: 14, option: "Belmopan", status: true)
Answer.create(question_id: 14, option: "Belice", status: false)
Answer.create(question_id: 14, option: "Santa Monica", status: false)
Answer.create(question_id: 15, option: "La Paz", status: true)
Answer.create(question_id: 15, option: "Buenos Aires", status: false)
Answer.create(question_id: 15, option: "Bogota", status: false)
Answer.create(question_id: 16, option: "Santiago", status: true)
Answer.create(question_id: 16, option: "Patagonia", status: false)
Answer.create(question_id: 16, option: "La Paz", status: false)
Answer.create(question_id: 17, option: "Otawa", status: true)
Answer.create(question_id: 17, option: "Columbia", status: false)
Answer.create(question_id: 17, option: "Niagara", status: false)
Answer.create(question_id: 18, option: "México", status: true)
Answer.create(question_id: 18, option: "Guanajuato", status: false)
Answer.create(question_id: 18, option: "Guadalajara", status: false)
Answer.create(question_id: 19, option: "Lima", status: true)
Answer.create(question_id: 19, option: "Cuzco", status: false)
Answer.create(question_id: 19, option: "Bolivia", status: false)
Answer.create(question_id: 20, option: "Puerto Principe", status: true)
Answer.create(question_id: 20, option: "Guatemala", status: false)
Answer.create(question_id: 20, option: "Costa Rica", status: false)

#Answers deck3
Answer.create(question_id: 21, option: "Paris", status: true)
Answer.create(question_id: 21, option: "Roma", status: false)
Answer.create(question_id: 21, option: "Berlin", status: false)
Answer.create(question_id: 22, option: "Madrid", status: true)
Answer.create(question_id: 22, option: "Barcelona", status: false)
Answer.create(question_id: 22, option: "Salamanca", status: false)
Answer.create(question_id: 23, option: "Roma", status: true)
Answer.create(question_id: 23, option: "Florencia", status: false)
Answer.create(question_id: 23, option: "Napoles", status: false)
Answer.create(question_id: 24, option: "Berlín", status: true)
Answer.create(question_id: 24, option: "Franckfur", status: false)
Answer.create(question_id: 24, option: "Trier", status: false)
Answer.create(question_id: 25, option: "Londres", status: true)
Answer.create(question_id: 25, option: "Hosmade", status: false)
Answer.create(question_id: 25, option: "Howarts", status: false)
Answer.create(question_id: 26, option: "Varsovia", status: true)
Answer.create(question_id: 26, option: "Poland", status: false)
Answer.create(question_id: 26, option: "Madrid", status: false)
Answer.create(question_id: 27, option: "Bruselas", status: true)
Answer.create(question_id: 27, option: "Berlín", status: false)
Answer.create(question_id: 27, option: "Santa Monica", status: false)
Answer.create(question_id: 28, option: "Vienna", status: true)
Answer.create(question_id: 28, option: "Eisenstand", status: false)
Answer.create(question_id: 28, option: "Villach", status: false)
Answer.create(question_id: 29, option: "Atenas", status: true)
Answer.create(question_id: 29, option: "Argos", status: false)
Answer.create(question_id: 29, option: "Roma", status: false)
Answer.create(question_id: 30, option: "Copenhague", status: true)
Answer.create(question_id: 30, option: "Berlin", status: false)
Answer.create(question_id: 30, option: "Madrid", status: false)

#Game
Game.create(user_id: 2, deck_id: 2, correct: 7, incorrect: 3)

#GameAnswer
Statistic.create(game_id: 1, question_id: 11, answer_id: 31)
Statistic.create(game_id: 1, question_id: 12, answer_id: 34)
Statistic.create(game_id: 1, question_id: 13, answer_id: 37)
Statistic.create(game_id: 1, question_id: 14, answer_id: 40)
Statistic.create(game_id: 1, question_id: 15, answer_id: 43)
Statistic.create(game_id: 1, question_id: 16, answer_id: 46)
Statistic.create(game_id: 1, question_id: 17, answer_id: 49)
Statistic.create(game_id: 1, question_id: 18, answer_id: 53)
Statistic.create(game_id: 1, question_id: 19, answer_id: 56)
Statistic.create(game_id: 1, question_id: 20, answer_id: 60)






